# Generated by Django 4.2.5 on 2024-03-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookthetable',
            old_name='name',
            new_name='customer_name',
        ),
    ]
