# Generated by Django 3.2.5 on 2024-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0002_rename_name_bookthetable_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
